name:  Auto Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan 185.65.68.235 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          run: |
          ssh -i ~/.ssh/id_ed25519 fruktoz@185.65.68.235 << 'EOF'
          cd tisztavaros/backend

           echo "Írom az .env fájlt..."
          cat > .env <<EOL
          PORT=3000
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_DIALECT=mysql
          EOL

            echo " Pulling latest code..."
            git pull origin main

            echo " Rebuilding services..."
            docker compose build

            cd ..
            echo " Restarting containers..."
            docker compose up -d --remove-orphans
          
          EOF
